services:
  stellar:
    image: stellar/quickstart:latest
    command: ["--local"]
    ports:
      - "8000:8000"
  
 # Unused in linux env 
 # container:
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
    
